In [2]:
import numpy as np
import pandas as pd
td=pd.read_csv('/content/beer-servings.csv')
td.head()

,Unnamed: 0,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,0,Afghanistan,0.0,0.0,0.0,0.0,Asia
1,1,Albania,89.0,132.0,54.0,4.9,Europe
2,2,Algeria,25.0,0.0,14.0,0.7,Africa
3,3,Andorra,245.0,138.0,312.0,12.4,Europe
4,4,Angola,217.0,57.0,45.0,5.9,Africa

In [3]:
td.columns

Index(['Unnamed: 0', 'country', 'beer_servings', 'spirit_servings',
       'wine_servings', 'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

In [4]:
td2=td.copy()

In [7]:
td2['beer_servings'].fillna(value=td2['beer_servings'].mean(),inplace=True)
td2['spirit_servings'].fillna(value=td2['spirit_servings'].mean(),inplace=True)
td2['wine_servings'].fillna(value=td2['wine_servings'].mean(),inplace=True)
td2['total_litres_of_pure_alcohol'].fillna(value=td2['total_litres_of_pure_alcohol'].mean(),inplace=True)

In [8]:
td2.isna().sum()

Unnamed: 0                      0
country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
continent                       0
dtype: int64

In [12]:
import scipy.stats as stats
td2['z_scores1'] = stats.zscore(td2['beer_servings'])
td2['z_scores2'] = stats.zscore(td2['spirit_servings'])
td2['z_scores3'] = stats.zscore(td2['wine_servings'])
td2['z_scores4'] = stats.zscore(td2['total_litres_of_pure_alcohol'])
td2.head()

,Unnamed: 0,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent,z_scores1,z_scores2,z_scores3,z_scores4
0,0,Afghanistan,0.0,0.0,0.0,0.0,Asia,-1.071026,-0.956134,-0.635910,-1.265092
1,1,Albania,89.0,132.0,54.0,4.9,Europe,-0.164278,0.560415,0.048603,0.042244
2,2,Algeria,25.0,0.0,14.0,0.7,Africa,-0.816322,-0.956134,-0.458444,-1.078329
3,3,Andorra,245.0,138.0,312.0,12.4,Europe,1.425080,0.629349,3.319058,2.043267
4,4,Angola,217.0,57.0,45.0,5.9,Africa,1.139810,-0.301261,-0.065482,0.309047

In [20]:
z_scores1=(np.abs(td2['z_scores1'])>3)

z_scores1.unique()

array([False])

In [22]:
z_scores2=(np.abs(td2['z_scores2'])>3)

z_scores2.value_counts()

z_scores2
False    191
True       2
Name: count, dtype: int64

In [23]:
z_scores3=(np.abs(td2['z_scores3'])>3)

z_scores3.value_counts()

z_scores3
False    190
True       3
Name: count, dtype: int64

In [24]:
z_scores4=(np.abs(td2['z_scores4'])>3)

z_scores4.value_counts()

z_scores4
False    193
Name: count, dtype: int64

**Shows outliers with in 2 columns spirit_servings and wine_servings**